### ISSUE TITLE
can ansj be memory-friendly?

### ISSUE THREAD

**Issue by heloowird** [NLPchina/ansj_seg#178]
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	    at java.util.LinkedList.superClone(Unknown Source)
	    at java.util.LinkedList.clone(Unknown Source)
	    at org.ansj.recognition.ForeignPersonRecognition.reset(ForeignPersonRecognition.java:119)
	    at org.ansj.recognition.ForeignPersonRecognition.recognition(ForeignPersonRecognition.java:92)
	    at org.ansj.splitWord.analysis.ToAnalysis$1.merger(ToAnalysis.java:49)
	    at org.ansj.splitWord.analysis.ToAnalysis.getResult(ToAnalysis.java:85)
	    at org.ansj.splitWord.Analysis.analysisStr(Analysis.java:140)
	    at org.ansj.splitWord.Analysis.parseStr(Analysis.java:218)
	    at org.ansj.splitWord.analysis.ToAnalysis.parse(ToAnalysis.java:117)
	    at era_misa.tm.util.FormatDocument.preProcess(FormatDocument.java:146)
	    at era_misa.tm.preprcs.StatWordFreq.statWordFreq(StatWordFreq.java:73)
	    at era_misa.tm.preprcs.StatWordFreq.main(StatWordFreq.java:160)

原始文档的总数为：403778     （*注：文档均为短文本，140字以内，你懂的*）
Eclipse运行参数：Arguments -Xmx2048m -Xms2048m

**Comment by ansjsun** [comment]
不会这么费内存的吧。请把你的文本发给我谢谢。。ansj-sun@163.com

**Comment by ansjsun** [comment]
Xmx2048m -Xms2048m 不要前面的arguments
