### ISSUE TITLE
[bug]单独运行词性标注的例子出错

### ISSUE THREAD

**Issue by NationalYu** [NLPchina/ansj_seg#186]
大神您好！
    我在运行http://nlpchina.github.io/ansj_seg/中的例子：
            String[] strs = {"对", "非", "ansj", "的", "分词", "结果", "进行", "词性", "标注"} ;
            List<String> lists = Arrays.asList(strs) ;
            List<Term> recognition = NatureRecognition.recognition(lists, 0) ;
            System.out.println(recognition);

报错，发现是空指针的问题，于是就下载项目修改好，上述错误不存在。
但是，当把修改好的项目打成jar包，被别的程序调用的时候，发现又报错了。
at org.nlpcn.commons.lang.util.IOUtil.getReader(IOUtil.java:63)
	at org.nlpcn.commons.lang.util.FileIterator.<init>(FileIterator.java:24)
	at org.nlpcn.commons.lang.util.IOUtil.instanceFileIterator(IOUtil.java:200)
	at org.nlpcn.commons.lang.dat.DoubleArrayTire.loadText(DoubleArrayTire.java:70)
	at org.ansj.library.DATDictionary.loadDAT(DATDictionary.java:46)
	at org.ansj.library.DATDictionary.<clinit>(DATDictionary.java:28)

您打好的jar包 ：ansj_seg-2.0.8.jar 是通过什么方法打的，能告诉一下吗？

**Comment by ansjsun** [comment]
这个bug将在3.x版本中修复。感谢您的意见。。
