### ISSUE TITLE
crf.model的内容有问题

### ISSUE THREAD

**Issue by thihy** [NLPchina/ansj_seg#195]
内容为：
Unexpected error.  File contents could not be restored from local history during undo/redo.

**Comment by thihy** [comment]
我看到有个Commit，说是去除CRF模型。现在是不使用CRF了么？在允许AnsjServer时，会报错：
java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:246)
	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:236)
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:140)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:56)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:65)
	at org.ansj.app.crf.Model.loadModel(Model.java:124)
	at org.ansj.util.MyStaticValue.getCRFSplitWord(MyStaticValue.java:282)
	at org.ansj.splitWord.analysis.NlpAnalysis.<clinit>(NlpAnalysis.java:35)
	at org.ansj.app.web.AnsjServer.main(AnsjServer.java:177)

**Comment by ansjsun** [comment]
对不起我们正在重构。。。 请你checkout 到这个版本上 https://github.com/NLPchina/ansj_seg/tree/853b3d0cd11c4ca873fc8ec8dce690e79d67592b

是正确的

**Comment by thihy** [comment]
后续还打算使用CRF么？怎么计算CRF模型呢？

**Comment by ansjsun** [comment]
必须打算后期模型和jar会分开 并且提供训练工具 是这么计划的


发自我的 iPhone
