### ISSUE TITLE
java.lang.NoClassDefFoundError: org/nlpcn/commons/lang/tire/domain/WoodInterface

### ISSUE THREAD

**Issue by huoxiaoduo** [NLPchina/ansj_seg#216]
使用的jar文件版本
ansj_seg-2.0.8.jar
nlp-lang-1.0.2.jar

运行异常
Exception in thread "main" java.lang.NoClassDefFoundError: org/nlpcn/commons/lang/tire/domain/WoodInterface
	at org.ansj.splitWord.Analysis.<init>(Analysis.java:42)
	at org.ansj.splitWord.analysis.NlpAnalysis.<init>(NlpAnalysis.java:112)
	at org.ansj.splitWord.analysis.NlpAnalysis.parse(NlpAnalysis.java:142)
	at org.ansj.app.keyword.KeyWordComputer.computeArticleTfidf(KeyWordComputer.java:57)
	at org.ansj.app.keyword.KeyWordComputer.computeArticleTfidf(KeyWordComputer.java:97)
	at Test.main(Test.java:16)
Caused by: java.lang.ClassNotFoundException: org.nlpcn.commons.lang.tire.domain.WoodInterface
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more

在 https://github.com/NLPchina/nlp-lang  项目中也没有发现提到的WoodInterface类

**Comment by ansjsun** [comment]
下载 3.0 all in one 吧一个jar包搞定了

[http://maven.nlpcn.org/org/ansj/ansj_seg/3.0/](http://maven.nlpcn.org/org/ansj/ansj_seg/3.0/)
