### ISSUE TITLE
和Lucene5.5集成问题，使用AnsjAnalyzer一直报错。

### ISSUE THREAD

**Issue by shijiebei2009** [NLPchina/ansj_seg#249]
com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 TestLucene,test
三月 23, 2016 10:35:19 上午 org.ansj.library.UserDefineLibrary loadFile
信息: init user userLibrary ok path is : D:\Multi-module-project\Lucene\src\main\resources\library\default.dic
三月 23, 2016 10:35:19 上午 org.ansj.library.UserDefineLibrary initAmbiguityLibrary
信息: init ambiguityLibrary ok!

java.lang.AssertionError: TokenStream implementation classes or at least their incrementToken() implementation must be final

	at org.apache.lucene.analysis.TokenStream.assertFinal(TokenStream.java:126)
	at org.apache.lucene.analysis.TokenStream.<init>(TokenStream.java:99)
	at org.apache.lucene.analysis.Tokenizer.<init>(Tokenizer.java:45)
	at org.ansj.lucene.util.AnsjTokenizer.<init>(AnsjTokenizer.java:26)
	at org.ansj.lucene5.AnsjAnalyzer.getTokenizer(AnsjAnalyzer.java:81)
	at org.ansj.lucene5.AnsjAnalyzer.createComponents(AnsjAnalyzer.java:67)
	at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:176)
	at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:205)
	at org.apache.lucene.queryparser.classic.QueryParserBase.newFieldQuery(QueryParserBase.java:479)
	at org.apache.lucene.queryparser.classic.QueryParserBase.getFieldQuery(QueryParserBase.java:471)
	at org.apache.lucene.queryparser.classic.QueryParserBase.handleBareTokenQuery(QueryParserBase.java:855)
	at org.apache.lucene.queryparser.classic.QueryParser.Term(QueryParser.java:348)
	at org.apache.lucene.queryparser.classic.QueryParser.Clause(QueryParser.java:247)
	at org.apache.lucene.queryparser.classic.QueryParser.Query(QueryParser.java:171)
	at org.apache.lucene.queryparser.classic.QueryParser.TopLevelQuery(QueryParser.java:160)
	at org.apache.lucene.queryparser.classic.QueryParserBase.parse(QueryParserBase.java:117)
	at TestLucene.test(TestLucene.java:102)
	

Process finished with exit code -1

**Comment by ansjsun** [comment]
我死了下如你所见没有发生你的错误.请把你的错误代码给我.我好更正谢谢

**Comment by shijiebei2009** [comment]
**Windows**：Win7 64 bit
**Java**：java version “1.8.0_45”；Java HotSpot(TM) 64-Bit Server VM
**Lucene**：5.5
**Jcseg**：1.9.7
**Ansj_seg**：3.7.1
**Ansj_lucene5_plug**：3.0
**Maven**：3.3.3

用的indextest你的测试代码

**Comment by shijiebei2009** [comment]
你是用的Ansj_lucene5_plug吗？

**Comment by thihy** [comment]
@shijiebei2009 这是由于Tokenizer编写不规范导致的。Lucene要求Tokenizer必须是不可继承的，也即class自己要是final，或者incToken方法是final的。可以不在Java启动参数中传递“ea”进行规避，也即禁用assert能力。

**Comment by shijiebei2009** [comment]
@thihy 可以在源码中添加final修复下。

**Comment by ansjsun** [comment]
好了试试吧 ...jar包没改  还3.7.1版本

http://maven.nlpcn.org/org/ansj/ansj_lucene5_plug/
