### ISSUE TITLE
UserDefineAnalysis 怎么在后续版本没有了

### ISSUE THREAD

**Issue by huoxiaoduo** [NLPchina/ansj_seg#265]
https://github.com/NLPchina/ansj_seg/issues/205

在3.2中增加了UserDefineAnalysis 支持了用户自定义词典

新版本(3.7.3) 中没有找到  3.2的版本还有

**Comment by huoxiaoduo** [comment]
`//以下内容只初始化一次,不用每次都加载

        List<String> readFile2List = IOUtil.readFile2List("keyword.dic","utf-8") ;

        for (String string : readFile2List) {
            Library.insertWord(UserDefineLibrary.FOREST, string);   
        }

        //over



        KeyWordComputer kw = new KeyWordComputer(5);

        List<Keyword> keywords = kw.computeArticleTfidf("2b族化合物 kw  2000 group 2b compounds航空飞机关键词搜索");

        for (Keyword keyword : keywords) {
            System.out.println(keyword);
        }
`

这段代码的demo也遇到了问题 

`信息: init core library ok use time :876
2016-4-26 15:46:16 org.ansj.library.NgramLibrary <clinit>
信息: init ngram ok use time :612
Exception in thread "main" java.lang.NullPointerException
	at org.ansj.splitWord.analysis.NlpAnalysis$1.merger(NlpAnalysis.java:77)
	at org.ansj.splitWord.analysis.NlpAnalysis.getResult(NlpAnalysis.java:125)
	at org.ansj.splitWord.Analysis.analysisStr(Analysis.java:122)
	at org.ansj.splitWord.Analysis.parseStr(Analysis.java:214)
	at org.ansj.splitWord.analysis.NlpAnalysis.parse(NlpAnalysis.java:175)
	at org.ansj.app.keyword.KeyWordComputer.computeArticleTfidf(KeyWordComputer.java:60)
	at org.ansj.app.keyword.KeyWordComputer.computeArticleTfidf(KeyWordComputer.java:116)
	at ansj_seg.Test.main(Test.java:34)`

**Comment by ansjsun** [comment]
不好意思 改成dicanalysis了

发自我的 iPhone

**Comment by yulei2019** [comment]
请问5.x版本如何是用路径的方式添加自定义词典
