### ISSUE TITLE
运行过程中发现小bug一个

### ISSUE THREAD

**Issue by xuyiqiang-learn** [NLPchina/ansj_seg#327]
org.ansj.app.crf.SplitWord的cut函数中(第44-45行，56-57行)，substring求子串有问题：
原码：
        `result.add(line.substring(begin, end);`
         `begin = end;`
应改为：
         `result.add(line.substring(begin, Math.min(end, line.length())));`
          `begin = Math.min(end, line.length());`
我这运行程序遇到这个问题。

**Comment by ansjsun** [comment]
你的意思..end可能大于line.length?

**Comment by xuyiqiang-learn** [comment]
嗯，我这运行遇到这个问题报错了啊，
`16/08/14 20:09:02 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 192.168.1.108:57832 (size: 8.3 KB, free: 8.3 GB)
16/08/14 21:11:35 WARN TaskSetManager: Lost task 5.0 in stage 0.0 (TID 5, 192.168.1.114): java.lang.StringIndexOutOfBoundsException: String index out of range: 59
        at java.lang.String.substring(String.java:1951)
        at org.ansj.app.crf.SplitWord.cut(SplitWord.java:57)
        at org.ansj.app.crf.SplitWord.cut(SplitWord.java:26)
        at org.ansj.splitWord.analysis.NlpAnalysis$1.merger(NlpAnalysis.java:80)
        at org.ansj.splitWord.analysis.NlpAnalysis.getResult(NlpAnalysis.java:184)
        at org.ansj.splitWord.Analysis.analysisStr(Analysis.java:133)
        at org.ansj.splitWord.Analysis.parseStr(Analysis.java:236)
        at org.ansj.splitWord.analysis.NlpAnalysis.parse(NlpAnalysis.java:280)
        at Utils$.parseWords(Utils.scala:42)`

**Comment by ansjsun** [comment]
能搞到那个例句吗?我这里试试..thx

**Comment by xuyiqiang-learn** [comment]
我自己修改后，重新运行，就没有问题了。

**Comment by ansjsun** [comment]
好吧.....我这里改了....我意思如果有例句我看看原因..可能背后还有其他事情要做

**Comment by xuyiqiang-learn** [comment]
我只是简单的封装了您的api
    def parseWords(sentence: String, filter: FilterRecognition): Array[String] = {
          val res4terrms: Result = NlpAnalysis.parse(sentence).recognition(filter)
          val terms: util.List[Term] = res4terrms.getTerms
           val array: Array[String] = new Array(terms.size)
           val iterator = terms.iterator()
           var i = 0
           while (iterator.hasNext) {
           array(i) = iterator.next().getName
           i += 1
      }
      array
    }

**Comment by ansjsun** [comment]
话说你的版本是?

**Comment by xuyiqiang-learn** [comment]
应为我是运行在集群上的，所以并不知道到底是哪个句子分词出了问题。

**Comment by xuyiqiang-learn** [comment]
分词是传入的句子过滤掉了null和空串

**Comment by xuyiqiang-learn** [comment]
最新版本的

**Comment by ansjsun** [comment]
是这两句吧?

````
for (int i = 0; i < size; i++) {
			e = elements.get(i);
			switch (e.getTag()) {
			case 0:
				end += e.len;
				result.add(line.substring(begin, end));
				begin = Math.min(end, line.length());
				break;
			case 1:
				end += e.len;
				while (i < size - 1 && (e = elements.get(++i)).getTag() != 3) {
					end += e.len;
				}
				end += e.len;
				result.add(line.substring(begin, end));
				begin = Math.min(end, line.length());
			default:
				break;
			}
		}
````

**Comment by xuyiqiang-learn** [comment]
对的

**Comment by ansjsun** [comment]
那就没问题了..回头发个5.0.2 会提上这个代码..感谢你的意见

**Comment by xuyiqiang-learn** [comment]
还有就是希望Recognition能够继承Serializable接口标记，并行化会报错

**Comment by xuyiqiang-learn** [comment]
我并行化时加入了过滤词表

**Comment by ansjsun** [comment]
好的加上

**Comment by xuyiqiang-learn** [comment]
没事，谢谢你们的无私奉献

**Comment by ansjsun** [comment]
````
public interface Recognition extends Serializable{
	public void recognition(Result result) ;
}

````

**Comment by xuyiqiang-learn** [comment]
嗯嗯

**Comment by xuyiqiang-learn** [comment]
刚才的第44-45行也要改。。。

**Comment by ansjsun** [comment]
我这里的代码行数和你的对应不上....
````
package crf;

import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedList;
import java.util.List;

import org.nlpcn.commons.lang.util.StringUtil;

import crf.model.Model;
import crf.pojo.Element;

/**
 * 分词
 * 
 * @author ansj
 * 
 */
public class SplitWord {

	private Model model = null;

	private Config config;

	public SplitWord(Model model) {
		this.model = model;
		this.config = model.getConfig();
	};

	public List<String> cut(String line) {

		if (StringUtil.isBlank(line)) {
			return Collections.emptyList();
		}

		List<Element> elements = vterbi(line);

		LinkedList<String> result = new LinkedList<String>();

		Element e = null;
		int begin = 0;
		int end = 0;

		int size = elements.size();

		for (int i = 0; i < size; i++) {
			e = elements.get(i);
			switch (e.getTag()) {
			case 0:
				end += e.len;
				result.add(line.substring(begin, end));
				begin = Math.min(end, line.length());
				break;
			case 1:
				end += e.len;
				while (i < size - 1 && (e = elements.get(++i)).getTag() != 3) {
					end += e.len;
				}
				end += e.len;
				result.add(line.substring(begin, end));
				begin = Math.min(end, line.length());
			default:
				break;
			}
		}
		// TODO: delete it
		// for (int i = 0; i < model.getConfig().tagNum; i++) {
		// for (int j = 0; j < model.getConfig().tagNum; j++) {
		// StringBuilder sb = new StringBuilder();
		// sb.append(((char) i));
		// sb.append(((char) j));
		// sb.append(((char) (150 + model.getConfig().getTemplate().length)));
		// model.printFeature(sb.toString());
		// }
		// }

		return result;
	}

	private List<Element> vterbi(String line) {
		List<Element> elements = config.makeToElementList(line);

		int length = elements.size();

		if (length == 1) {
			elements.get(0).updateTag(0);
			return elements;
		}
		/**
		 * 填充图
		 */
		for (int i = 0; i < length; i++) {
			computeTagScore(elements, i);
		}

		for (int i = 1; i < length; i++) {
			elements.get(i).maxFrom(model, elements.get(i - 1));
		}

		// 末位置只能从0,3开始
		Element next = elements.get(elements.size() - 1);
		Element self = null;
		int maxStatus = next.tagScore[0] > next.tagScore[3] ? 0 : 3;
		next.updateTag(maxStatus);
		maxStatus = next.from[maxStatus];
		// 逆序寻找
		for (int i = elements.size() - 2; i > 0; i--) {
			self = elements.get(i);
			self.updateTag(maxStatus);
			maxStatus = self.from[self.getTag()];
			next = self;
		}
		elements.get(0).updateTag(maxStatus);

		// printElements(elements) ;

		return elements;

	}

	/**
	 * 调试时候观察变量用
	 * 
	 * @param elements
	 */
	private static void printElements(List<Element> elements) {
		System.out.println("--------------------------------");
		for (Element element : elements) {
			System.out.println(element.getName() + "\t" + Arrays.toString(element.tagScore));
		}
	}

	private void computeTagScore(List<Element> elements, int index) {

		double[] tagScore = new double[config.tagNum];

		List<String> makeFeature = model.getConfig().makeFeature(elements, index);

		for (String featureStr : makeFeature) {
			// model.printFeature(featureStr) ;
			dot(tagScore, model.getFeatureIndex(featureStr));
		}

		elements.get(index).tagScore = tagScore;
	}

	public void dot(double[] tagScore, int featureIndex) {

		if (featureIndex < 0) {
			return;
		}

		for (int i = 0; i < tagScore.length; i++) {
			tagScore[i] += model.getWeight(featureIndex * config.tagNum + i);
		}
	}
}

````

这是完整的类没错了吧?

**Comment by xuyiqiang-learn** [comment]
cut函数的case0的substring没改

**Comment by xuyiqiang-learn** [comment]
cut函数的两处substring要改为：result.add(line.substring(begin, end)？，可以不用改？

**Comment by xuyiqiang-learn** [comment]
cut函数的两处substring需要修改为result.add(line.substring(begin, Math.min(end, line.length())))？还是不用修改？

**Comment by ansjsun** [comment]
应该不用改..所有end赋值都是e.len 应该不会出问题的,其实你那个超.我也很奇怪.....理论上不会呀..我跑了至少几十g的文本.也没发现你说的那个问题...

**Comment by xuyiqiang-learn** [comment]
我不清楚具体是哪，运行时除了几次警告

**Comment by xuyiqiang-learn** [comment]
出了了几次这样的警告，task老是failed

**Comment by ansjsun** [comment]
先改成这样试试吧..要是有问题再改..理论上不会了....应该

**Comment by xuyiqiang-learn** [comment]
嗯，好的，谢谢

**Comment by ansjsun** [comment]
我仔细看了下代码..理论上不可能越界..下次能trycatch下吗?如果发生错误..想办法把错误例句搞到..我这里就方便改了....暂时先这样看看.效果吧

**Comment by xuyiqiang-learn** [comment]
好的，后面再处理

**Comment by 315445896** [comment]
可以复现：
NlpAnalysis.parse("公司因本章程第二十九條第（三）項、第（五）")
