### ISSUE TITLE
加载训练的语料程序报错

### ISSUE THREAD

**Issue by moshangshaoguang** [NLPchina/ansj_seg#342]
MyStaticValue.CRF.put(MyStaticValue.CRF_DEFAULT, "D:/fenci/CRF++-0.58/test/model.txt") ;
log.info("ddd",NlpAnalysis.parse("北京支付宝钱袋有限公司"));
10:56:01.015 [main] INFO DICLOG - begin init crf model!
10:56:01.019 [main] WARN CRF - 解压异常
java.util.zip.ZipException: Not in GZIP format
    at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
    at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
    at org.ansj.app.crf.model.CRFModel.checkModel(CRFModel.java:66)
    at org.ansj.app.crf.Model.load(Model.java:55)
    at org.ansj.util.MyStaticValue.initCRFModel(MyStaticValue.java:377)
    at org.ansj.util.MyStaticValue.getCRFSplitWord(MyStaticValue.java:332)
    at org.ansj.util.MyStaticValue.getCRFSplitWord(MyStaticValue.java:312)
    at org.ansj.splitWord.analysis.NlpAnalysis.<init>(NlpAnalysis.java:48)
    at org.ansj.splitWord.analysis.NlpAnalysis.parse(NlpAnalysis.java:280)
    at com.a11315.service.ceshiTest.ceshiTest(ceshiTest.java:35)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
10:56:01.021 [main] INFO DICLOG - crf file : D:/fenci/CRF++-0.58/test/model.txt load err err tag named U in model null
10:56:01.381 [main] INFO DICLOG - init core library ok use time :351
10:56:01.731 [main] INFO DICLOG - init ngram ok use time :345
10:56:01.771 [main] WARN DICLOG - not find any crf model, make sure your config right? 
10:56:01.773 [main] INFO com.a11315.service.ceshiTest - ddd

**Comment by ansjsun** [comment]
初步来看你的标记和我的不配套导致的。。

xt load err err tag named U in model null


load需要用     Model model  =new CRFppTxtModel("");

详细你可以参看此wiki

https://github.com/NLPchina/ansj_seg/wiki/%E5%AE%9A%E5%88%B6%E4%BD%A0%E8%87%AA%E5%B7%B1%E7%9A%84CRF%E6%A8%A1%E5%9E%8B

**Comment by moshangshaoguang** [comment]
帮忙再看一下这个问题，是格式的问题，还是我训练模版的问题
      下面是所有的代码:
        MyStaticValue.CRF.put(MyStaticValue.CRF_DEFAULT, "D:/fenci/CRF++-0.58/test/model.txt") ;
        Model model = new CRFppTxtModel("");
        model.loadModel("D:\\fenci\\CRF++-0.58\\test\\model.txt");
        Result Result=NlpAnalysis.parse("北京钱袋宝支付科技有限公司");
        log.info("sssssss=====>"+Result);
-----------------------------------------------------------------------------------------------
 1、 Model model = new CRFppTxtModel("");
       model.loadModel("D:\\fenci\\CRF++-0.58\\test\\model.txt");
我只运行这两行代码的时候是正常的，说明训练的模型格式应该符合要求了吧，但是注释掉这两行代码时
 2、 MyStaticValue.CRF.put(MyStaticValue.CRF_DEFAULT, "D:/fenci/CRF++-0.58/test/model.txt") ;
       Result Result=NlpAnalysis.parse("北京钱袋宝支付科技有限公司");
       log.info("sssssss=====>"+Result);
      程序报错了
09:46:29.598 [main] INFO DICLOG - init ambiguityLibrary ok!
09:46:29.599 [main] INFO DICLOG - begin init crf model!
09:46:29.605 [main] WARN CRF - 解压异常
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.ansj.app.crf.model.CRFModel.checkModel(CRFModel.java:66)
	at org.ansj.app.crf.Model.load(Model.java:55)
	at org.ansj.util.MyStaticValue.initCRFModel(MyStaticValue.java:377)
	at org.ansj.util.MyStaticValue.getCRFSplitWord(MyStaticValue.java:332)
	at org.ansj.util.MyStaticValue.getCRFSplitWord(MyStaticValue.java:312)
	at org.ansj.splitWord.analysis.NlpAnalysis.<init>(NlpAnalysis.java:48)
	at org.ansj.splitWord.analysis.NlpAnalysis.parse(NlpAnalysis.java:280)
	at com.a11315.service.ceshiTest.ceshiTest(ceshiTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
09:46:29.607 [main] INFO CRF - load template ok template : [-2] [-1] [0] [1] [2] [-2, -1, 0] [-1, 0, 1] [0, 1, 2] [-1, 0] [0, 1] 
09:46:31.846 [main] INFO CRF - load feature ok feature size : 698701
09:46:33.599 [main] INFO CRF - load crfpp model ok ! use time :3993
09:46:33.599 [main] INFO DICLOG - load crf use time:4000 path is : D:/fenci/CRF++-0.58/test/model.txt
09:46:33.878 [main] INFO DICLOG - init core library ok use time :269
09:46:34.279 [main] INFO DICLOG - init ngram ok use time :395
09:46:34.327 [main] INFO com.a11315.service.ceshiTest - sssssss=====>北京钱袋宝支付科技有限/nt,公司/n

Process finished with exit code 0
肯请帮忙解答。

**Comment by ansjsun** [comment]
这个不要    
 MyStaticValue.CRF.put(MyStaticValue.CRF_DEFAULT, "D:/fenci/CRF++-0.58/test/model.txt") ;

应该内部判断是哪种模型的..可以把你模型的前100行发给我吗?我check下

**Comment by moshangshaoguang** [comment]
记 B
者 M
从 M
吉 M
林 M
省 M
粮 M
食 M
局 M
获 M
悉 M
， M
该 M
省 M
num4 M
年 M
国 M
家 M
临 M
时 M
存 M
储 M
玉 M
米 M
收 M
购 M
工 M
作 M
在 M
num1 M
月 M
num2 M
日 M
结 M
束 M
。 M
自 M
去 M
年 M
num2 M
月 M
num1 M
日 M
启 M
动 M
收 M
购 M
以 M
来 M
， M
吉 M
林 M
全 M
省 M
共 M
入 M
库 M
国 M
家 M
临 M
时 M
存 M
储 M
玉 M
米 M
num3 M
, M
num1 M
亿 M
斤 M
， M
创 M
执 M
行 M
国 M
家 M
临 M
时 M
存 M
储 M
玉 M
米 M
收 M
购 M
政 M
策 M
以 M
来 M
新 M
高 M
。 E
截 B
至 M
num1 M
月 M
num2 M
日 M
， M
吉 M
林 M
累 M
计 M
收 M
购 M
新 M
粮 M
num4 M
, M
num1 M
亿 M
斤 M
， M
同 M
比 M
增 M
加 M
num3 M
, M
num1 M
亿 M
斤 M
。 M
其 M
中 M
， M
玉 M
米 M
num4 M
亿 M
斤 M
（ M

还一个是
version: 100
cost-factor: 1
maxid: 2726924
xsize: 1

B
E
M
S

U00:%x[-2,0]
U01:%x[-1,0]
U02:%x[0,0]
U03:%x[1,0]
U04:%x[2,0]
U05:%x[-2,0]/%x[-1,0]/%x[0,0]
U06:%x[-1,0]/%x[0,0]/%x[1,0]
U06:%x[-2,0]/%x[-1,0]
U07:%x[-1,0]/%x[0,0]
U08:%x[0,0]/%x[1,0]
U09:%x[1,0]/%x[2,0]
B

10816 B
2549940 U00:!
1143140 U00:#
13856 U00:%
26144 U00:&
15112 U00:(
15264 U00:)
23140 U00:*
276596 U00:+
2388 U00:,
22660 U00:-
22820 U00:/
793300 U00::
10280 U00:;
316092 U00:=
2613700 U00:@
44 U00:_B-1
0 U00:_B-2
2067316 U00:en0
22528 U00:en1
22752 U00:en2
22848 U00:en3
252344 U00:en4
101520 U00:en5
204648 U00:en6
168868 U00:en7
252320 U00:en8
1730020 U00:num0
1344 U00:num1
1432 U00:num2
2348 U00:num3
684 U00:num4
64464 U00:num5
80644 U00:num6
653660 U00:num7
101244 U00:num8
1816820 U00:num9
1110100 U00:|
85716 U00:~
955564 U00:ɑ
1831060 U00:ˉ
317312 U00:ц
2090468 U00:​
1831216 U00:‐
317200 U00:℃
607396 U00:Ⅰ
607488 U00:Ⅳ
1377344 U00:≦
204036 U00:■
439248 U00:□
487848 U00:●
10888 U00:　
7748 U00:、
1604 U00:。
29668 U00:《
29900 U00:》
337976 U00:【
338056 U00:】
99596 U00:〔
99644 U00:〕
35536 U00:一
663040 U00:丁
404676 U00:七
65908 U00:万
490476 U00:丈
12564 U00:三
39656 U00:上
17096 U00:下
13400 U00:不
34848 U00:与
1275556 U00:丑
85828 U00:专
39556 U00:且
14360 U00:世
1237920 U00:丘
103804 U00:丙
8924 U00:业
1749188 U00:丛
18736 U00:东
35576 U00:丝
707712 U00:丢
5304 U00:两
5900 U00:严
2152608 U00:丧
4976 U00:个
3600 U00:中
160180 U00:丰
704836 U00:串
860 U00:临
485024 U00:丸
366484 U00:丹
3980 U00:为
5796 U00:主
556736 U00:丽
65364 U00:举
549464 U00:乃
121860 U00:久
112152 U00:么
55480 U00:义
33036 U00:之
472112 U00:乌
224560 U00:乎
85280 U00:乏
232932 U00:乐
1262872 U00:乔
1454828 U00:乖
538536 U00:乘
468380 U00:乙
457756 U00:九
41076 U00:也
143440 U00:习
5196 U00:乡
49792 U00:书
123548 U00:买
242016 U00:乱
24848 U00:乳
1474656 U00:乾
1915676 U00:亁
30296 U00:了
18268 U00:予
69200 U00:争
32848 U00:事
34424 U00:二
10616 U00:于
200996 U00:亏
134380 U00:云
234724 U00:互
230260 U00:五
83228 U00:井
73072 U00:亚
42476 U00:些
342176 U00:亟
98572 U00:亡
33856 U00:交
1589216 U00:亦
8608 U00:产
1744228 U00:亨
440140 U00:亩
583768 U00:享
26432 U00:京
779392 U00:亭
301796 U00:亮
532208 U00:亲
316472 U00:亳
9008 U00:人
2460 U00:亿
112120 U00:什
80208 U00:仁
62380 U00:仅
82800 U00:仆
73160 U00:今
50492 U00:介
163548 U00:仍
176 U00:从
168976 U00:仑
42064 U00:仓
851476 U00:仔
319608 U00:仕
27576 U00:他
447680 U00:付
609124 U00:仙
1480244 U00:仟
75880 U00:代
74376 U00:令
1968 U00:以
6832 U00:仪
42316 U00:们
1738856 U00:仰
915620 U00:仲
111140 U00:件
6324 U00:价
25492 U00:任
25804 U00:份
167960 U00:仿
14432 U00:企
336412 U00:伊
139576 U00:伍
778024 U00:伏
137988 U00:伐
133544 U00:休
224068 U00:众
70232 U00:优
240024 U00:伙
42864 U00:会
645228 U00:伟
75212 U00:传
345924 U00:伤
332716 U00:伦
125940 U00:伪
915588 U00:伯
208576 U00:估
141464 U00:伴
1981896 U00:伸
141724 U00:似
53072 U00:但
62000 U00:位
我没弄明白你要哪个模型，索性都给你贴上了

**Comment by ansjsun** [comment]
用第二个模型.
````
	private Model model = new CRFppTxtModel("CRFppModelTest");

	@Before
	public void before() throws Exception {
		if (!Check.checkFileExit(modelPath)) {
			return;
		}
		model.loadModel(modelPath);

SplitWord sw = new SplitWord(model);

		System.out.println(sw.cut("瓦西里斯的船只中有４０％驶向远东，每个月几乎都有两三条船停靠中国港口。"));

	}



````

用这种方式加载,如果还不行把模型发我邮箱ansj-sun@163.com

**Comment by moshangshaoguang** [comment]
String modelPath = "D:/fenci/CRF++-0.58/test/model.txt";
    private Model model = new CRFppTxtModel("CRFppModelTest");
    @Test
    public void ceshiTest() throws Exception {
        // MyStaticValue.CRF.put(MyStaticValue.CRF_DEFAULT, "D:/fenci/CRF++-0.58/test/model.txt") ;
//        Model model = new CRFppTxtModel("");
//        model.loadModel("D:\\fenci\\CRF++-0.58\\test\\model.txt");
        log.info("sssssss=====>" + NlpAnalysis.parse("北京字节跳动科技有限公司"));
    }

    @Before
    public void before() throws Exception {
//        if (!Check.checkFileExit(modelPath)) {=============》这个Check没有找到对应的类，所以我就注释掉了，这行应该是就是去检测模版路径是否为空
//            return;
//        }
        model.loadModel(modelPath);
        SplitWord sw = new SplitWord(model);
        System.out.println(sw.cut("瓦西里斯的船只中有４０％驶向远东，每个月几乎都有两三条船停靠中国港口。"));
    }
这样程序是正常的，但是分词的结果就有区别，下面程序没报错的情况下出现的分词结果：
15:17:14.423 [main] INFO CRF - load template ok template : [-2] [-1] [0] [1] [2] [-2, -1, 0] [-1, 0, 1] [-2, -1] [-1, 0] [0, 1] [1, 2] 
15:17:15.172 [main] INFO CRF - load feature ok feature size : 219259
15:17:15.864 [main] INFO CRF - load crfpp model ok ! use time :1447
[瓦西里斯的船只中有４０％驶向远东，每个月几乎都有两三条船停靠中国港口。]
15:17:15.903 [main] INFO CRF - load template ok template : [-2] [-1] [0] [1] [2] [-2, -1, 0] [-1, 0, 1] [-2, -1] [-1, 0] [0, 1] [1, 2] 
15:17:16.274 [main] INFO CRF - load feature ok feature size : 219259
15:17:17.002 [main] INFO CRF - load crfpp model ok ! use time :1098
15:17:17.622 [main] ERROR DICLOG - not find field by crfModel
15:17:17.623 [main] ERROR DICLOG - not find field by userLibrary
15:17:17.623 [main] WARN DICLOG - init userLibrary  warning :D:\IdeaWorkSpace\company-name-service\company-service-impl\library\default.dic because : file not found or failed to read !
15:17:17.623 [main] ERROR DICLOG - init ambiguity  error in line :习近平	习近平	nr format err !
15:17:17.623 [main] ERROR DICLOG - init ambiguity  error in line :李民工作	李民	nr	工作	vn format err !
15:17:17.623 [main] ERROR DICLOG - init ambiguity  error in line :三个和尚	三个	m	和尚	n format err !
15:17:17.623 [main] ERROR DICLOG - init ambiguity  error in line :的确定不	的确	d	定	v	不	v format err !
15:17:17.623 [main] ERROR DICLOG - init ambiguity  error in line :大和尚	大	a	和尚	n format err !
15:17:17.623 [main] ERROR DICLOG - init ambiguity  error in line :张三和	张三	nr	和	c format err !
15:17:17.623 [main] ERROR DICLOG - init ambiguity  error in line :动漫游戏	动漫	n	游戏	n format err !
15:17:17.624 [main] ERROR DICLOG - init ambiguity  error in line :邓颖超生前	邓颖超	nr	生前	t format err !
15:17:17.624 [main] INFO DICLOG - init ambiguityLibrary ok!
15:17:17.624 [main] INFO DICLOG - init deafult crf model begin !
15:17:18.763 [main] INFO CRF - load crf model ok ! use time :1138
15:17:19.027 [main] INFO DICLOG - init core library ok use time :258
15:17:19.307 [main] INFO DICLOG - init ngram ok use time :275
15:17:19.315 [main] INFO com.a11315.service.ceshiTest - sssssss=====>北京字节/nw,跳动/v,科技有限公司/nt
===============================================================
在一个就是程序报错的情况下分词的结果：（原因就是：MyStaticValue.CRF.put(MyStaticValue.CRF_DEFAULT, "D:/fenci/CRF++-0.58/test/model.txt") ;没有注释掉这行）
15:25:28.556 [main] INFO CRF - load template ok template : [-2] [-1] [0] [1] [2] [-2, -1, 0] [-1, 0, 1] [-2, -1] [-1, 0] [0, 1] [1, 2] 
15:25:29.296 [main] INFO CRF - load feature ok feature size : 219259
15:25:29.990 [main] INFO CRF - load crfpp model ok ! use time :1441
[瓦西里斯的船只中有４０％驶向远东，每个月几乎都有两三条船停靠中国港口。]
15:25:30.664 [main] ERROR DICLOG - not find field by crfModel
15:25:30.664 [main] ERROR DICLOG - not find field by userLibrary
15:25:30.667 [main] WARN DICLOG - init userLibrary  warning :D:\IdeaWorkSpace\company-name-service\company-service-impl\library\default.dic because : file not found or failed to read !
15:25:30.667 [main] ERROR DICLOG - init ambiguity  error in line :习近平	习近平	nr format err !
15:25:30.668 [main] ERROR DICLOG - init ambiguity  error in line :李民工作	李民	nr	工作	vn format err !
15:25:30.668 [main] ERROR DICLOG - init ambiguity  error in line :三个和尚	三个	m	和尚	n format err !
15:25:30.668 [main] ERROR DICLOG - init ambiguity  error in line :的确定不	的确	d	定	v	不	v format err !
15:25:30.668 [main] ERROR DICLOG - init ambiguity  error in line :大和尚	大	a	和尚	n format err !
15:25:30.668 [main] ERROR DICLOG - init ambiguity  error in line :张三和	张三	nr	和	c format err !
15:25:30.668 [main] ERROR DICLOG - init ambiguity  error in line :动漫游戏	动漫	n	游戏	n format err !
15:25:30.668 [main] ERROR DICLOG - init ambiguity  error in line :邓颖超生前	邓颖超	nr	生前	t format err !
15:25:30.668 [main] INFO DICLOG - init ambiguityLibrary ok!
15:25:30.668 [main] INFO DICLOG - begin init crf model!
15:25:30.671 [main] WARN CRF - 解压异常
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.ansj.app.crf.model.CRFModel.checkModel(CRFModel.java:66)
	at org.ansj.app.crf.Model.load(Model.java:55)
	at org.ansj.util.MyStaticValue.initCRFModel(MyStaticValue.java:377)
	at org.ansj.util.MyStaticValue.getCRFSplitWord(MyStaticValue.java:332)
	at org.ansj.util.MyStaticValue.getCRFSplitWord(MyStaticValue.java:312)
	at org.ansj.splitWord.analysis.NlpAnalysis.<init>(NlpAnalysis.java:48)
	at org.ansj.splitWord.analysis.NlpAnalysis.parse(NlpAnalysis.java:280)
	at com.a11315.service.ceshiTest.ceshiTest(ceshiTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
15:25:30.672 [main] INFO CRF - load template ok template : [-2] [-1] [0] [1] [2] [-2, -1, 0] [-1, 0, 1] [-2, -1] [-1, 0] [0, 1] [1, 2] 
15:25:31.050 [main] INFO CRF - load feature ok feature size : 219259
15:25:31.786 [main] INFO CRF - load crfpp model ok ! use time :1115
15:25:31.786 [main] INFO DICLOG - load crf use time:1118 path is : D:/fenci/CRF++-0.58/test/model.txt
15:25:32.080 [main] INFO DICLOG - init core library ok use time :287
15:25:32.420 [main] INFO DICLOG - init ngram ok use time :336
15:25:32.428 [main] INFO com.a11315.service.ceshiTest - sssssss=====>北京字节跳动科技有限公司/nt
说明这是受到了训练的模板的影响

**Comment by gaohuitang** [comment]
你好，moshangshaoguang。请问您通过训练语料之后，能把“北京字节跳动科技有限公司”作为一个整体分出来吗？

**Comment by moshangshaoguang** [comment]
@gaohuitang 并不能，因为我训练的crf.model不知道怎么去控制所以就放弃了
