### ISSUE TITLE
无法加载CRF训练模型

### ISSUE THREAD

**Issue by CHARLESYAN1** [NLPchina/ansj_seg#349]
参照文档，训练CRF，错误代码如下

Sep 10, 2016 11:50:10 PM DICLOG info
INFO: init user userLibrary ok path is : /Users/Charles/Documents/workspace/textAnalysis/library/library/default.dic
Sep 10, 2016 11:50:10 PM DICLOG info
INFO: init user userLibrary ok path is : /Users/Charles/Documents/workspace/textAnalysis/library/library/financeword.dic
Sep 10, 2016 11:50:10 PM DICLOG info
INFO: init ambiguityLibrary ok!
Sep 10, 2016 11:50:10 PM DICLOG info
INFO: begin init crf model!
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.String.charAt(String.java:658)
    at org.ansj.app.crf.model.CRFppTxtModel.loadTagCoven(CRFppTxtModel.java:237)
    at org.ansj.app.crf.model.CRFppTxtModel.loadModel(CRFppTxtModel.java:52)
    at org.ansj.app.crf.Model.load(Model.java:75)
    at org.ansj.util.MyStaticValue.initCRFModel(MyStaticValue.java:378)
    at org.ansj.util.MyStaticValue.getCRFSplitWord(MyStaticValue.java:332)
    at org.ansj.util.MyStaticValue.getCRFSplitWord(MyStaticValue.java:312)
    at org.ansj.splitWord.analysis.NlpAnalysis.<init>(NlpAnalysis.java:51)
    at org.ansj.splitWord.analysis.NlpAnalysis.parse(NlpAnalysis.java:288)
    at segment.demo.main(demo.java:23)
Sep 10, 2016 11:50:10 PM DICLOG info
INFO: crf file : /Users/Charles/Documents/workspace/textAnalysis/test/CRF++-0.58/test/model.txt load err String index out of range: 0
Sep 10, 2016 11:50:11 PM DICLOG info
INFO: init core library ok use time :594
Sep 10, 2016 11:50:12 PM DICLOG info
INFO: init ngram ok use time :938
Sep 10, 2016 11:50:12 PM DICLOG warn
WARNING: not find crf model you can you can visit http://maven.nlpcn.org/down/ to down it ! 
欢迎/v,使用/v,Ansj/en,的/uj,CRF/en,功能/n,!

求解！谢谢

<img width="801" alt="screen shot 2016-09-10 at 23 50 16" src="https://cloud.githubusercontent.com/assets/17907872/18415257/abcc75f6-77b1-11e6-8d62-51cca3aae63a.png">

**Comment by CHARLESYAN1** [comment]
https://github.com/NLPchina/ansj_seg/wiki/定制你自己的CRF模型
就是按照这个一步一步来的

**Comment by CHARLESYAN1** [comment]
这个是5.0.0版本的error message, 
5.0.2是
<img width="802" alt="screen shot 2016-09-10 at 23 58 02" src="https://cloud.githubusercontent.com/assets/17907872/18415287/6d8973e2-77b2-11e6-9b7f-50b236ba3ca3.png">

代码没有任何改动

**Comment by ansjsun** [comment]
可能是我的过..看样子你模型不是gzip压缩后的..你应该用CRFModel方式加载..

**Comment by JaneVinWin** [comment]
@ansjsun 你好这个问题解决了吗？ 我也碰到同样的问题

**Comment by kelciej** [comment]
这个 crf.model 这个文件的格式是gzip的，不知道 @ansjsun 为什么要这么写。但是我格式改完之后，还是出现了很多莫名其妙的错误
