### ISSUE TITLE
老bug，自定义词典类似“汽车车标”同类重叠字分词问题，描述如下

### ISSUE THREAD

**Issue by javahaohao** [NLPchina/ansj_seg#358]
ansj版本：5.0.2
nlp-lang版本:1.7
用户自定义词典中加入"汽车车标"，然后用用户自定义词性优先解析器报错，如下：

``` java
public static void main(String[] args) {
       UserDefineLibrary.insertWord("汽车车标", "userDefine", 1000);
       System.out.println(DicAnalysis.parse("汽车标").getTerms());//北汽车衣,不锈钢三维汽车标
}
```

``` java
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 4
    at org.ansj.util.Graph.getMaxTerm(Graph.java:164)
    at org.ansj.util.Graph.rmLittlePath(Graph.java:127)
    at org.ansj.splitWord.analysis.DicAnalysis$1.userDefineRecognition(DicAnalysis.java:66)
    at org.ansj.splitWord.analysis.DicAnalysis$1.merger(DicAnalysis.java:38)
    at org.ansj.splitWord.analysis.DicAnalysis.getResult(DicAnalysis.java:85)
    at org.ansj.splitWord.Analysis.analysisStr(Analysis.java:133)
    at org.ansj.splitWord.Analysis.parseStr(Analysis.java:236)
    at org.ansj.splitWord.analysis.DicAnalysis.parse(DicAnalysis.java:106)
```

**Comment by ansjsun** [comment]
e  ..这个应该是已经修复过了的.我本地木有这bug.但是5.02的确存在..5.03已经修正..正在快马加鞭提交到maven仓库中...

**Comment by javahaohao** [comment]
辛苦了！很期待新版本提交

**Comment by ansjsun** [comment]
已修复
