### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundException: 1

### ISSUE THREAD

**Issue by walkerlala** [NLPchina/ansj_seg#376]
你好，为何我在读取文件然后对里面的每一个句子进行分词之后，会得到这个Exception？
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at org.ansj.splitWord.Analysis.analysisStr(Analysis.java:112)
	at org.ansj.splitWord.Analysis.parseStr(Analysis.java:213)
	at org.ansj.splitWord.analysis.NlpAnalysis.parse(NlpAnalysis.java:142)    <- 这里出现问题
	at Classifier.splitWords(Classifier.java:115)
	at Classifier.loadData(Classifier.java:89)
	at Classifier.main(Classifier.java:346)
```

奇怪的是，测试没有问题：

```
List<Term> termList = NlpAnalysis.parse("你们好啊");
```

这个是没有问题的。但是，如果函数参数换成一个`String`类型的变量，就会出现问题:
```
List<Term> termList = NlpAnalysis.parse(mystr);    //mystr of type String
```

会是什么原因？编码问题？
谢谢！

**Comment by sunyonggang** [comment]
我的这段代码没问题：
```
    val s = "这是第一个猴子"
    val r = NlpAnalysis.parse(s);
    println(r)

output:
   这/r,是/v,第一个/m,猴子/n
```
能详细点描述你的问题么？👀

**Comment by walkerlala** [comment]
如果将字符串直接写到代码里，是没有问题的。但是如果从文件中读入字符串然后再分词就会有问题：
```
InputStream IP = new BufferedInputStream(new FileInputStream("myfile"));
Scanner sc = new Scanner(IP).useDelimiter("\r\n");
while(sc.hasnext()){
    String sss = sc.next();    //我在这里还做了一点split()处理，但是返回类型还是String
    List<Term> termList = new NlpAnalysis.parse(sss);   //<-这一句直接就Exception了
}
```

**Comment by walkerlala** [comment]
我用的是3.7.3-all-in-one版本，换成5.0.2版本后就没有这个问题了。怀疑是不能完全正确自动识别编码的问题。

**Comment by ansjsun** [comment]
额。。解决了就好我们现在用的都是5.x了
