### ISSUE TITLE
楼主昨晚修改了什么内容，我下载5.0.1的jar，执行基本ToAnalysis.parse(str)报错，信息如下

### ISSUE THREAD

**Issue by yangbisheng2009** [NLPchina/ansj_seg#384]
Exception in thread "main" java.lang.NoClassDefFoundError: org/nlpcn/commons/lang/tire/domain/Forest
	at org.ansj.splitWord.analysis.ToAnalysis.parse(ToAnalysis.java:101)
	at testansj.com.yangfg.App.main(App.java:14)
Caused by: java.lang.ClassNotFoundException: org.nlpcn.commons.lang.tire.domain.Forest
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

**Comment by ansjsun** [comment]
5.0.1 的jar没有改动..你检查下nlp-lang.jar是否版本对应..这个jar最好用maven依赖..不要自己导入...ps 现在最新出到5.0.4 了把..
