### ISSUE TITLE
对含有“大”字的文本进行分词会报错

### ISSUE THREAD

**Issue by zyc825onDataMining** [NLPchina/ansj_seg#394]
刚开始尝试用java做分词，遇到了一些问题：
执行  System.out.println(ToAnalysis.parse("大"));   会报如下错误：
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 3
	at org.ansj.splitWord.Analysis.analysisStr(Analysis.java:112)
	at org.ansj.splitWord.Analysis.parseStr(Analysis.java:213)
	at org.ansj.splitWord.analysis.ToAnalysis.parse(ToAnalysis.java:99)
	at wordSegment.WordSegmentTest.main(WordSegmentTest.java:14)
所有带“大”字的文本都会报该类错误，而不带“大”字的文本能够正常分词，向请教一下是什么原因造成的

**Comment by ansjsun** [comment]
请问你的分词版本是??之前我的确发现过这个bug..但是应该没这么严重吧....当时只有一个大字在DIcAnalysis中会报错

**Comment by zyc825onDataMining** [comment]
ansj_seg-2.0.8; npl-lang-1.0.是否换个版本能避免这种情况呢

**Comment by ansjsun** [comment]
换版本应该可以解决 现在都5.x了


发自我的 iPhone

**Comment by zyc825onDataMining** [comment]
5.x不会出现这种问题了，感谢帮助
