### ISSUE TITLE
我是菜鸟一个,,刚开始学习这个,这个错误是怎么回事

### ISSUE THREAD

**Issue by lanyunhaixing** [NLPchina/ansj_seg#413]
Exception in thread "main" java.lang.NoSuchMethodError: love.cq.domain.SmartForest.<init>(D)V
	at org.ansj.app.crf.Model.loadModel(Model.java:145)
	at org.ansj.util.MyStaticValue.getCRFSplitWord(MyStaticValue.java:299)
	at org.ansj.splitWord.analysis.NlpAnalysis.<clinit>(NlpAnalysis.java:35)
	at org.ansj.app.keyword.KeyWordComputer.computeArticleTfidf(KeyWordComputer.java:58)
	at org.ansj.app.keyword.KeyWordComputer.computeArticleTfidf(KeyWordComputer.java:98)
	at sdcncsi.ict.mdtj.anjian.ceshi.main(ceshi.java:36)

**Comment by ansjsun** [comment]
这个分词版本太旧太旧了
