### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by jayzlee147** [NLPchina/ansj_seg#421]
能帮忙看看这个溢出是什么原因吗？代码是用scala写的。
```
import org.ansj.app.crf.model.CRFppTxtModel
import org.ansj.splitWord.analysis.NlpAnalysis
import org.ansj.util.MyStaticValue

object CRF{
  def main(args: Array[String]) {
    val model = new CRFppTxtModel("CRFppModelTest")
    val modelPath = "D:/code/demo/library/model.txt"
    model.loadModel(modelPath)
    println(NlpAnalysis.parse("观澜人才网最新招聘信息"))
  }
}
```

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at org.nlpcn.commons.lang.tire.domain.SmartForest.add(SmartForest.java:102)
	at org.nlpcn.commons.lang.tire.domain.SmartForest.add(SmartForest.java:186)
	at org.ansj.app.crf.model.CRFppTxtModel.loadFeatureWeight(CRFppTxtModel.java:204)
	at org.ansj.app.crf.model.CRFppTxtModel.loadModel(CRFppTxtModel.java:60)
	at com.demo.CRF$.main(tb.scala:12)
	at com.demo.CRF.main(tb.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by ansjsun** [comment]
内存太小了

**Comment by ansjsun** [comment]
给jvm的内存大点

**Comment by jayzlee147** [comment]
-Xms128m
-Xmx4096m
-XX:MaxPermSize=350m
-XX:ReservedCodeCacheSize=240m
-XX:+UseConcMarkSweepGC
-XX:SoftRefLRUPolicyMSPerMB=50
-ea
-Dsun.io.useCanonCaches=false
-Djava.net.preferIPv4Stack=true
-XX:+HeapDumpOnOutOfMemoryError
-XX:-OmitStackTraceInFastThrow


配置文件改成这样还是不够呢   是配置改的不对吗     我看模型只有110M左右

**Comment by jayzlee147** [comment]
还有如果用wiki里面给的这种加载模型方式会有解压错误呢？
```
import org.ansj.app.crf.model.CRFppTxtModel
import org.ansj.splitWord.analysis.NlpAnalysis
import org.ansj.util.MyStaticValue

object CRF{
  def main(args: Array[String]) {
      MyStaticValue.CRF.put(MyStaticValue.CRF_DEFAULT, "D:/code/demo/library/model.txt")
      println(NlpAnalysis.parse("观澜人才网最新招聘信息"))
  }
}
```
2017-02-15 15:47:11,429 WARN [CRF] - 解压异常
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at org.ansj.app.crf.model.CRFModel.checkModel(CRFModel.java:66)
	at org.ansj.app.crf.Model.load(Model.java:55)
	at org.ansj.util.MyStaticValue.initCRFModel(MyStaticValue.java:377)
	at org.ansj.util.MyStaticValue.getCRFSplitWord(MyStaticValue.java:332)
	at org.ansj.util.MyStaticValue.getCRFSplitWord(MyStaticValue.java:312)
	at org.ansj.splitWord.analysis.NlpAnalysis.<init>(NlpAnalysis.java:48)
	at org.ansj.splitWord.analysis.NlpAnalysis.parse(NlpAnalysis.java:280)
	at com.demo.CRF$.main(tb.scala:13)
	at com.demo.CRF.main(tb.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by ansjsun** [comment]
NlpAnalysis nlpAnalysis = new NlpAnalysis() ;
			nlpAnalysis.setCrfModel(new SplitWord(Model.load("D:/code/demo/library/model.txt"))) ;
			System.out.println(nlpAnalysis.parseStr("aaaaaaaaaaa"));


试试这个...

**Comment by ansjsun** [comment]
NlpAnalysis nlpAnalysis = new NlpAnalysis() ;
			nlpAnalysis.setCrfModel(new SplitWord(CRFppTxtModel.load("D:/code/demo/library/model.txt"))) ;
			System.out.println(nlpAnalysis.parseStr("aaaaaaaaaaa"));

**Comment by jayzlee147** [comment]
还想问一下可以同时加载CRF模型和自定义词典进行分词吗？可以的话怎么加载，有没有先后顺序的问题？
