### ISSUE TITLE
lucene 6.4.1 + ansj_seg 5.1.1 + ansj_lucene6_plug 5.1.1.0 会出现错误

### ISSUE THREAD

**Issue by ywjno** [NLPchina/ansj_seg#441]
在使用 lucene 6.4.1 + ansj_seg 5.1.1 + ansj_lucene6_plug 5.1.1.0 时，在 `indexWriter.addDocument` 方法时会出现以下错误

```
Exception in thread "main" java.lang.IllegalArgumentException: first position increment must be > 0 (got 0) for field 'text'
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:727)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:417)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:373)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:232)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:449)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1492)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1271)
	at com.peikore.LuceneTest.lambda$writerIndex$0(LuceneTest.java:101)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.ywjno.LuceneTest.writerIndex(LuceneTest.java:74)
	at com.ywjno.LuceneTest.main(LuceneTest.java:39)
```

但是在使用 lucene 6.4.1 + ansj_seg 5.0.4 + ansj_lucene6_plug 5.0.4 时却没这个问题

**Comment by ansjsun** [comment]
已修复...现在发布到maven仓库..估计还得几个小时才能看到..下载最新的5.1.1的plugin应该可以解决...
