### ISSUE TITLE
动态添加同义词NullPointerException

### ISSUE THREAD

**Issue by wcong** [NLPchina/ansj_seg#509]
本地没有同义词文件，通过代码动态添加的时候NullPointerException   
看代码是init方法里加载本地文件出错，会删除key，后面的findAllWords在取得时候没有判空  
版本: 5.1.1  
调用方法:
```
SynonymsLibrary.insert(SynonymsLibrary.DEFAULT, new String[] { "兰多", "兰少" });
```
异常栈:
```
java.lang.NullPointerException
	at org.ansj.library.SynonymsLibrary.findAllWords(SynonymsLibrary.java:207)
	at org.ansj.library.SynonymsLibrary.insert(SynonymsLibrary.java:187)
```

**Comment by ansjsun** [comment]
只能再调用钱自己put个进去像这个

````
SynonymsLibrary.put(SynonymsLibrary.DEFAULT,SynonymsLibrary.DEFAULT,new SmartForest<List<String>>());
		SynonymsLibrary.insert(SynonymsLibrary.DEFAULT, new String[] { "兰多", "兰少" });
````
