### ISSUE TITLE
生产环境报错java.lang.IllegalArgumentException: position increments (and gaps) must be >= 0 (got 8929048) for field 'summary'

### ISSUE THREAD

**Issue by leter** [NLPchina/ansj_seg#515]
但是在本地测试环境没有问题，感觉非常奇怪。好像是超过600字的文件就会出现这个问题。
版本如下：
jdk7.0 
tomcat8
ansj_lucene5_plug-5.1.1.2
ansj_seg-5.1.2
lucene-analyzers-common-5.5.4
文本如下：
[工程名称]赣州市南康区第四中学学生公寓、食堂及附属工程
[关键信息]赣州市南康区第四中学.; 房屋建筑工 程施工总承包叁级以上(含叁级)资质;无;本工程授权委托人(注册建造师)须提供劳动合同和投标公司为其缴交的社保证明（社保证明时间为2015 年 11 月至 2016 年 1 月）原件，须提供加盖当地社保局业务章的社保手册或花名册(含姓名、社保查询号或身份证号、缴费基数和缴费凭证)或基本养老保险个人帐户对账单；如果建造师是法人代表的，则提供：身份证、法人代表资格证、建造师注册证书及其相应的 B 类安全生产考核合格证；               须提交公司或投标项目所 在地的检察机关出具的投标公司和投标公 司拟派项目负责人的《关于行贿犯罪档案 查询通知书》 。;小胡开银诚、中灿两家，赣州市南康区第四中学学生公寓、食堂及附属工程，本项目投资 857.9 万元，开标时间：2016 年 03 月 01 日 10:00，投标保证金的金额：15 万元，保证金到账截止时间为 2016 年 2月 26 日 17:00 时。介绍信2000元/家，报名费600元/家，保证金老板自己打。开标老板：黄思婷 134-0707-4912    委托人：胡童科。;2000.0;
[其他信息]赣州分公司;赣州分公司;投标申请单-20160226-1;3607821602050117-1.JXZF;;

报错信息如下：

```java
[ERROR][2017-06-21 10:44:12][类com.fastwork.bm.common.lucene.LuceneUtil的第89行]-[错误信息[批量创建索引的时候发生异常,索引信息[Document<stored,indexed,omitNorms,indexOptions=DOCS<id:10501> stored,indexed,omitNorms,indexOptions=DOCS<fk:Project_BidApply> stored,indexed,tokenized<summary:[工程名称]赣州市南康区第四中学学生公寓、食堂及附属工程
[关键信息]赣州市南康区第四中学.; 房屋建筑工 程施工总承包叁级以上(含叁级)资质;无;本工程授权委托人(注册建造师)须提供劳动合同和投标公司为其缴交的社保证明（社保证明时间为2015 年 11 月至 2016 年 1 月）原件，须提供加盖当地社保局业务章的社保手册或花名册(含姓名、社保查询号或身份证号、缴费基数和缴费凭证)或基本养老保险个人帐户对账单；如果建造师是法人代表的，则提供：身份证、法人代表资格证、建造师注册证书及其相应的 B 类安全生产考核合格证；               须提交公司或投标项目所 在地的检察机关出具的投标公司和投标公 司拟派项目负责人的《关于行贿犯罪档案 查询通知书》 。;小胡开银诚、中灿两家，赣州市南康区第四中学学生公寓、食堂及附属工程，本项目投资 857.9 万元，开标时间：2016 年 03 月 01 日 10:00，投标保证金的金额：15 万元，保证金到账截止时间为 2016 年 2月 26 日 17:00 时。介绍信2000元/家，报名费600元/家，保证金老板自己打。开标老板：黄思婷 134-0707-4912    委托人：胡童科。;2000.0;
[其他信息]赣州分公司;赣州分公司;投标申请单-20160226-1;3607821602050117-1.JXZF;;> indexed,omitNorms,indexOptions=DOCS<uid:2324Project_BidApply> indexed,omitNorms,indexOptions=DOCS<did:1246Project_BidApply> indexed,omitNorms,indexOptions=DOCS<rid:11207Project_BidApply> stored,indexed,omitNorms,indexOptions=DOCS<valid:1> stored,indexed,tokenized,omitNorms,indexOptions=DOCS,numericType=INT,numericPrecisionStep=8<date:20160226> docValuesType=NUMERIC<date_sort:20160226>>]]java.lang.IllegalArgumentException: position increments (and gaps) must be >= 0 (got 9404990) for field 'summary'
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:649)
	at org.apache.lucene.index.DefaultIndexingChain.processField(DefaultIndexingChain.java:365)
	at org.apache.lucene.index.DefaultIndexingChain.processDocument(DefaultIndexingChain.java:321)
	at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:234)
	at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:450)
	at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1477)
	at org.apache.lucene.index.IndexWriter.addDocument(IndexWriter.java:1256)
	at com.fastwork.bm.common.lucene.LuceneUtil.addDocuments(LuceneUtil.java:246)
	at com.fastwork.bm.common.lucene.job.BuildIndexTask.buildIndex(BuildIndexTask.java:171)
	at com.fastwork.bm.common.lucene.job.BuildIndexTask.buildIndex(BuildIndexTask.java:96)
	at com.fastwork.bm.common.lucene.job.BuildLuceneIndexJob.run(BuildLuceneIndexJob.java:42)
	at com.fastwork.bm.common.job.BaseJob.work(BaseJob.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:321)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:111)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Comment by ansjsun** [comment]
你好你是用的原生的lucene吗?
我在本地测试时没有这个问题的.看样子是position increments 错误导致.
先确认下生产环境的版本是否是最新版本.

最好能找到出错的文本..用如下程序出错

````
package org.ansj.ansj_lucene5_plug;

import java.io.IOException;
import java.io.StringReader;

import org.ansj.domain.Term;
import org.ansj.library.DicLibrary;
import org.ansj.lucene5.AnsjAnalyzer;
import org.ansj.lucene5.AnsjAnalyzer.TYPE;
import org.ansj.splitWord.analysis.IndexAnalysis;
import org.ansj.util.MyStaticValue;
import org.apache.lucene.analysis.Analyzer;
import org.apache.lucene.analysis.TokenStream;
import org.apache.lucene.analysis.miscellaneous.PerFieldAnalyzerWrapper;
import org.apache.lucene.document.Document;
import org.apache.lucene.document.Field.Store;
import org.apache.lucene.document.TextField;
import org.apache.lucene.index.CorruptIndexException;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.IndexWriterConfig;
import org.apache.lucene.index.IndexableField;
import org.apache.lucene.queryparser.classic.ParseException;
import org.apache.lucene.queryparser.classic.QueryParser;
import org.apache.lucene.search.IndexSearcher;
import org.apache.lucene.search.Query;
import org.apache.lucene.search.TopDocs;
import org.apache.lucene.search.highlight.Highlighter;
import org.apache.lucene.search.highlight.InvalidTokenOffsetsException;
import org.apache.lucene.search.highlight.QueryScorer;
import org.apache.lucene.search.highlight.SimpleHTMLFormatter;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.RAMDirectory;
import org.junit.Test;

public class IndexAndTest {

	@Test
	public void test() throws Exception {
		DicLibrary.put(DicLibrary.DEFAULT, "../../library/default.dic");
		PerFieldAnalyzerWrapper analyzer = new PerFieldAnalyzerWrapper(new AnsjAnalyzer(TYPE.index_ansj));
		Directory directory = null;
		IndexWriter iwriter = null;

		IndexWriterConfig ic = new IndexWriterConfig(analyzer);

		String text = "[工程名称]赣州市南康区第四中学学生公寓、食堂及附属工程\n" + 
				"[关键信息]赣州市南康区第四中学.; 房屋建筑工 程施工总承包叁级以上(含叁级)资质;无;本工程授权委托人(注册建造师)须提供劳动合同和投标公司为其缴交的社保证明（社保证明时间为2015 年 11 月至 2016 年 1 月）原件，须提供加盖当地社保局业务章的社保手册或花名册(含姓名、社保查询号或身份证号、缴费基数和缴费凭证)或基本养老保险个人帐户对账单；如果建造师是法人代表的，则提供：身份证、法人代表资格证、建造师注册证书及其相应的 B 类安全生产考核合格证；               须提交公司或投标项目所 在地的检察机关出具的投标公司和投标公 司拟派项目负责人的《关于行贿犯罪档案 查询通知书》 。;小胡开银诚、中灿两家，赣州市南康区第四中学学生公寓、食堂及附属工程，本项目投资 857.9 万元，开标时间：2016 年 03 月 01 日 10:00，投标保证金的金额：15 万元，保证金到账截止时间为 2016 年 2月 26 日 17:00 时。介绍信2000元/家，报名费600元/家，保证金老板自己打。开标老板：黄思婷 134-0707-4912    委托人：胡童科。;2000.0;\n" + 
				"[其他信息]赣州分公司;赣州分公司;投标申请单-20160226-1;3607821602050117-1.JXZF;;";

		System.out.println(IndexAnalysis.parse(text));

		// 建立内存索引对象
		directory = new RAMDirectory();
		iwriter = new IndexWriter(directory, ic);
		addContent(iwriter, text);
		iwriter.commit();
		iwriter.close();

		System.out.println("索引建立完毕");

		Analyzer queryAnalyzer = new AnsjAnalyzer(AnsjAnalyzer.TYPE.index_ansj);

		System.out.println("index ok to search!");

		for (Term t : IndexAnalysis.parse(text)) {
			System.out.println(t.getName());
			search(queryAnalyzer, directory, "\"" + t.getName() + "\"");
		}

	}

	private void search(Analyzer queryAnalyzer, Directory directory, String queryStr) throws CorruptIndexException, IOException, ParseException {
		IndexSearcher isearcher;
		DirectoryReader directoryReader = DirectoryReader.open(directory);
		// 查询索引
		isearcher = new IndexSearcher(directoryReader);
		QueryParser tq = new QueryParser("text", queryAnalyzer);
		Query query = tq.parse(queryStr);
		System.out.println(query);
		TopDocs hits = isearcher.search(query, 5);
		System.out.println(queryStr + ":共找到" + hits.totalHits + "条记录!");
		for (int i = 0; i < hits.scoreDocs.length; i++) {
			int docId = hits.scoreDocs[i].doc;
			Document document = isearcher.doc(docId);
			System.out.println(toHighlighter(queryAnalyzer, query, document));
		}
	}

	private void addContent(IndexWriter iwriter, String text) throws CorruptIndexException, IOException {
		Document doc = new Document();
		IndexableField field = new TextField("text", text, Store.YES);
		doc.add(field);
		iwriter.addDocument(doc);
	}

	/**
	 * 高亮设置
	 * 
	 * @param query
	 * @param doc
	 * @param field
	 * @return
	 */
	private String toHighlighter(Analyzer analyzer, Query query, Document doc) {
		String field = "text";
		try {
			SimpleHTMLFormatter simpleHtmlFormatter = new SimpleHTMLFormatter("<font color=\"red\">", "</font>");
			Highlighter highlighter = new Highlighter(simpleHtmlFormatter, new QueryScorer(query));
			TokenStream tokenStream1 = analyzer.tokenStream("text", new StringReader(doc.get(field)));
			String highlighterStr = highlighter.getBestFragment(tokenStream1, doc.get(field));
			return highlighterStr == null ? doc.get(field) : highlighterStr;
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvalidTokenOffsetsException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return null;
	}

}

````

**Comment by leter** [comment]
很奇怪，单独执行的时候不会出问题，只有大批量创建索引的时候才会偶发性的出现这个问题。不知道是不是因为批量执行的时候导致内部索引混乱的缘故。还有的的Analyzer是单例模式的，不知道和这有没有关系？

**Comment by shi-yuan** [comment]
不用单例试试

**Comment by leter** [comment]
好的，谢谢。

**Comment by leter** [comment]
刚刚试过了，Analyzer不用单例模式就没出问题了。。。看样子Analyzer不是线程安全的类。

**Comment by ansjsun** [comment]
是的静态调用方法内部也是每次new一个..analyzer对象是有上下文的.必须每次new额
