### ISSUE TITLE
序列化Term时出现抛出java.lang.StackOverflowError异常

### ISSUE THREAD

**Issue by gzn555823** [NLPchina/ansj_seg#528]
Exception in thread "main" java.lang.StackOverflowError
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)...
语料很大的话想把分词结果完整保留下来还有什么方法吗？

**Comment by shibing624** [comment]
自己写个调用分词的存储方法，一部分一部分保存结果到各个小文件中。

**Comment by ansjsun** [comment]
可能内存溢出了。建议保存为json。。格式然后序列化。不要直接序列化对象
