### ISSUE TITLE
NullPointerException at PersonRecognition.java:161

### ISSUE THREAD

**Issue by jcjview** [NLPchina/ansj_seg#574]
Exception in thread "main" java.lang.NullPointerException
	at org.ansj.recognition.arrimpl.PersonRecognition$2.step(PersonRecognition.java:161)
	at org.nlpcn.commons.lang.viterbi.Node.<init>(Node.java:48)
	at org.nlpcn.commons.lang.viterbi.Viterbi.<init>(Viterbi.java:24)
	at org.ansj.recognition.arrimpl.PersonRecognition.recognition(PersonRecognition.java:158)
	at org.ansj.splitWord.analysis.ToAnalysis$1.merger(ToAnalysis.java:43)
	at org.ansj.splitWord.analysis.ToAnalysis.getResult(ToAnalysis.java:74)
	at org.ansj.splitWord.Analysis.analysisStr(Analysis.java:149)
	at org.ansj.splitWord.Analysis.parseStr(Analysis.java:257)
	at org.ansj.splitWord.analysis.ToAnalysis.parse(ToAnalysis.java:86)
	at org.ansj.test.AmbiguityTest.main(AmbiguityTest.java:27)

in version：
Merge: 3185ffd 0b7c938
Author: ansj <ansj-sun@163.com>
Date:   Mon Nov 6 12:21:38 2017 +0800

    Merge pull request #572 from shi-yuan/master

    完善词频统计
step:

git clone  repo 

run AmbiguityTest

**Comment by ansjsun** [comment]
感谢提交英国已经修复了
