### ISSUE TITLE
加载自己的model出错

### ISSUE THREAD

**Issue by chilejiang1024** [NLPchina/ansj_seg#579]
### 现状
通过CRF++-0.58 在centOS系统上训练得到的train.txt(部分)如下
```
一 B
耕 M
（ M
北 M
京 M
） M
科 M
技 M
发 M
展 M
有 M
限 M
公 M
司 E
```
learn后得到的model如下
```
y��  K����  �f���  �J���  ����  wF���  ����  �_���  ����  _Q���  �  z  
  z    z  
  z    z    z  !  z  "  z  $  z  )  z  *  z  ,  z  /  z  3  z  5  z  �q��
  ���  7  z  ����
```
就全变成乱码了, 使用如下方法加载报错 
```
    public static void main(String[] args) {
        try {
            CRFppTxtModel model = new CRFppTxtModel().loadModel("D:\\model");
            System.out.println(new SplitWord(model).cut("北京****有限公司"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
错误信息为
```
java.lang.Exception: err tag named � in model null
	at org.ansj.app.crf.model.CRFppTxtModel.loadTagCoven(CRFppTxtModel.java:287)
	at org.ansj.app.crf.model.CRFppTxtModel.loadModel(CRFppTxtModel.java:88)
	at org.ansj.app.crf.model.CRFppTxtModel.loadModel(CRFppTxtModel.java:48)
	at org.ansj.app.crf.model.CRFppTxtModel.main(CRFppTxtModel.java:33)
```

这是怎么个问题呢 .... 需要改进的地方是 .....

**Comment by chilejiang1024** [comment]
### 补充一点
这里是想提高机构名(准确的说是公司名)识别的准确度, 或者是否有更好的办法来做到这点? 请给于建议, 谢谢~

**Comment by chilejiang1024** [comment]
可以给点建议么?

**Comment by chaoliu1024** [comment]
检查下txt文本是不是utf-8格式

**Comment by chilejiang1024** [comment]
转为UTF8格式了, 我又重新训练了一遍.
现在报错是这样的:
```
15:51:35.794 [main] INFO org.ansj.app.crf.Model - load template ok template : [-1] [0] [1] [-1, 0] [0, 1] [-1, 1] 
java.lang.Exception: can find feature named "" in [""]
```

**Comment by chilejiang1024** [comment]
![image](https://user-images.githubusercontent.com/16152022/32824837-80d4ab74-ca1d-11e7-8dcd-031b32a704d3.png)

**Comment by ansjsun** [comment]
好多人告诉我crfmodel有问题。。能把。这个模型发我一份吗我试试。可能加载的时候我没有写全面
