### ISSUE TITLE
java.lang.NoClassDefFoundError: Lucene 4.7 on Android

### ISSUE THREAD

**Issue by bizkitj** [NLPchina/ansj_seg#685]
你好。非常感谢开源这个工具。
在集成到Android里面的时候出了这个问题：

`implementation group: 'org.apache.lucene', name: 'lucene-memory', version: '4.7.0'
implementation group: 'org.apache.lucene', name: 'lucene-core', version: '4.7.0'
implementation group: 'org.apache.lucene', name: 'lucene-queryparser', version: '4.7.0'
implementation group: 'org.apache.lucene', name: 'lucene-highlighter', version: '4.7.0'
implementation group: 'org.apache.lucene', name: 'lucene-queries', version: '4.7.0'
implementation group: 'org.apache.lucene', name: 'lucene-join', version: '4.7.0'
implementation group: 'org.ansj', name: 'ansj_lucene4_plug', version: '5.0.2'`

`compileSdkVersion 27`
`minSdkVersion  16`

`java.lang.NoClassDefFoundError: Failed resolution of: Lorg/ansj/splitWord/analysis/ToAnalysis;
        at org.ansj.lucene4.AnsjAnalysis.createComponents(AnsjAnalysis.java:41)
        at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:180)
        at org.apache.lucene.document.Field.tokenStream(Field.java:552)
        at org.apache.lucene.index.DocInverterPerField.processFields(DocInverterPerField.java:103)
        at org.apache.lucene.index.DocFieldProcessor.processDocument(DocFieldProcessor.java:248)
        at org.apache.lucene.index.DocumentsWriterPerThread.updateDocument(DocumentsWriterPerThread.java:253)
        at org.apache.lucene.index.DocumentsWriter.updateDocument(DocumentsWriter.java:453)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1529)
        at org.apache.lucene.index.IndexWriter.updateDocument(IndexWriter.java:1502)`

谢谢

**Comment by ansjsun** [comment]
是不是没有导入 ansj的jar包?


<dependency>
    <groupId>org.ansj</groupId>
    <artifactId>ansj_seg</artifactId>
    <version>5.0.2</version>
</dependency>

**Comment by bizkitj** [comment]
> 是不是没有导入 ansj的jar包?
> // https://mvnrepository.com/artifact/org.ansj/ansj_seg
> `compile group: 'org.ansj', name: 'ansj_seg', version: '5.0.2'`

是的，谢谢，导入之后，可以了。非常感谢。
