### ISSUE TITLE
EmailRecognitionTest 用例失败

### ISSUE THREAD

**Issue by Alanscut** [NLPchina/ansj_seg#756]
由于List初始化长度不合理，导致数组越界指针异常。
https://github.com/NLPchina/ansj_seg/blob/2b5b4a511ddc5eb78f57eda9254d687f55d5e0a4/src/main/java/org/ansj/recognition/impl/ExtractingRecognition.java#L57

```
java.lang.IllegalArgumentException: Illegal Capacity: -2

	at java.util.ArrayList.<init>(ArrayList.java:157)
	at org.ansj.recognition.impl.ExtractingRecognition.recognition(ExtractingRecognition.java:57)
	at org.ansj.domain.Result.recognition(Result.java:53)

```

**Comment by Alanscut** [comment]
fixed by #757.
